[package]
name = "lru_cache_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "lru_cache_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.24.0"
lru = "0.7.3"
